project:
  type: website
  output-dir: docs
  
website:
  title: "Yashaswi Lal"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    tools:
      - icon: LinkedIN
        href: https://twitter.com/
      - icon: github
        href: https://github.com/yashaswiL/mywebsite
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Yashaswi Lal"

format:
  html:
    theme: yeti
    toc: true

editor: source

